## 内置提示词
define EXAMP_REQUIREMENT

试题要求，整套试卷包括：10 道单选题（20分），10 道判断题（10分），填空题10个空（20分），5 道名词解释题目（10分）, 4 道问答或计算题（40分）。
出题要求：
* 同样的知识点，考察不要超过两次。
* 考题分布尽量平均，各章节都涉及到。

endef


## 触发工作流
default: 考点.txt

.ONESHELL: 考点.txt
考点.txt:
	@echo "请输入课程名称："
	@read -p "=> " COURSE_NAME
	@if [ -z "$$COURSE_NAME" ]; then echo "谢谢使用！"; exit ; fi
	
	ifl -y -s ./config_exam.yaml -t "请生成 $$COURSE_NAME 相关考试考点表，考点略微详细一点，按两层章节罗列，知识点考察点文件保存为 '考点.txt'"


